### ISSUE TITLE
Unit-Test

### ISSUE THREAD

**Issue by maxrbc** [OSCAR-LAB/Ara-MicroBench#4]
We have not approach at all any for of testing for our design in any of the classes or implementations ( and that includes me ) If we can get Anshal into playing with that part too it would be amazing... @pardeep0101 any opinion about it ?

**Comment by pardeep0101** [comment]
That would be awesome, but if you have time today we can have a small talk to further discuss the code and solve some of my doubts about git. :D

**Comment by maxrbc** [comment]
Today im a bit on schedule but tomorrow afternoon im fine. Just let me know time so i can plan around that

**Comment by pardeep0101** [comment]
okay, how about 12:30 pm?

**Comment by maxrbc** [comment]
I think its possible. Nonetheless ill confirm tomorrow.

**Comment by pardeep0101** [comment]
sure, no problem.

**Comment by pardeep0101** [comment]
Just a reminder for today's meeting.

**Comment by maxrbc** [comment]
Meeting between 12:30 - 1:30
